In [1]:
import gensim.downloader as api
wv=api.load("word2vec-google-news-300")

In [2]:
wv.similarity(w1="great",w2="good")

0.729151

In [3]:
# to see the vector of a particular word
wv["good"]

array([ 0.04052734,  0.0625    , -0.01745605,  0.07861328,  0.03271484,
       -0.01263428,  0.00964355,  0.12353516, -0.02148438,  0.15234375,
       -0.05834961, -0.10644531,  0.02124023,  0.13574219, -0.13183594,
        0.17675781,  0.27148438,  0.13769531, -0.17382812, -0.14160156,
       -0.03076172,  0.19628906, -0.03295898,  0.125     ,  0.25390625,
        0.12695312, -0.15234375,  0.03198242,  0.01135254, -0.01361084,
       -0.12890625,  0.01019287,  0.23925781, -0.08447266,  0.140625  ,
        0.13085938, -0.04516602,  0.06494141,  0.02539062,  0.05615234,
        0.24609375, -0.20507812,  0.23632812, -0.00860596, -0.02294922,
        0.05078125,  0.10644531, -0.03564453,  0.08740234, -0.05712891,
        0.08496094,  0.23535156, -0.10107422, -0.03564453, -0.04736328,
        0.04736328, -0.14550781, -0.10986328,  0.14746094, -0.23242188,
       -0.07275391,  0.19628906, -0.37890625, -0.07226562,  0.04833984,
        0.11914062,  0.06103516, -0.12109375, -0.27929688,  0.05200195,
        0.04907227, -0.02709961,  0.1328125 ,  0.03369141, -0.32226562,
        0.04223633, -0.08789062,  0.15429688,  0.09472656,  0.10351562,
       -0.02856445,  0.00128174, -0.00427246,  0.24609375, -0.05957031,
       -0.16894531, -0.09619141,  0.16796875,  0.0133667 ,  0.04882812,
        0.08349609,  0.06347656, -0.00872803, -0.08642578, -0.03857422,
       -0.08251953,  0.15722656,  0.22753906, -0.00762939, -0.19921875,
       -0.06347656,  0.12792969, -0.06347656, -0.03027344,  0.0456543 ,
        0.06298828, -0.02526855, -0.06787109, -0.01141357, -0.13574219,
        0.02978516,  0.10400391, -0.15917969, -0.08447266,  0.29882812,
       -0.12597656,  0.11425781, -0.08105469, -0.09082031, -0.07910156,
       -0.11181641, -0.09619141,  0.02770996,  0.14257812, -0.26757812,
       -0.09375   ,  0.03979492, -0.17871094, -0.02819824,  0.01464844,
       -0.31640625, -0.24511719, -0.08935547,  0.09716797, -0.00964355,
       -0.14746094,  0.15234375,  0.21582031,  0.05981445,  0.23828125,
       -0.05151367,  0.14941406,  0.13574219, -0.03222656, -0.265625  ,
       -0.11181641, -0.23046875, -0.140625  ,  0.25585938, -0.15429688,
        0.1796875 ,  0.15527344, -0.21582031,  0.36328125, -0.1015625 ,
        0.04980469,  0.07177734, -0.14550781, -0.03198242,  0.00952148,
       -0.12109375,  0.12109375,  0.09765625,  0.07763672,  0.3203125 ,
       -0.22265625, -0.08447266, -0.10742188,  0.11279297, -0.13867188,
       -0.21875   ,  0.0145874 ,  0.13378906, -0.00921631,  0.00921631,
        0.16894531,  0.16894531, -0.078125  , -0.00665283,  0.03735352,
       -0.10888672, -0.25390625,  0.01452637, -0.09716797, -0.19628906,
       -0.01782227, -0.28125   , -0.02050781, -0.02905273, -0.09375   ,
       -0.17675781,  0.21484375, -0.05224609, -0.11572266, -0.01977539,
       -0.10839844, -0.01342773, -0.15332031, -0.140625  , -0.11816406,
        0.09228516,  0.109375  ,  0.05761719, -0.03466797,  0.03564453,
       -0.12011719, -0.14257812, -0.00072479, -0.06689453,  0.11914062,
       -0.10449219,  0.07861328, -0.12792969,  0.09570312, -0.00817871,
        0.07128906,  0.20703125, -0.03149414,  0.09570312,  0.17285156,
       -0.07958984, -0.02429199, -0.07519531, -0.07568359,  0.09521484,
       -0.06494141, -0.00689697, -0.09033203,  0.03100586,  0.19921875,
       -0.10644531, -0.11474609,  0.18652344, -0.05078125,  0.0859375 ,
        0.00128937, -0.18847656, -0.20019531, -0.02832031,  0.11328125,
        0.25976562,  0.22070312,  0.04101562,  0.00171661,  0.07568359,
       -0.01196289,  0.0177002 , -0.05883789, -0.25976562, -0.234375  ,
       -0.04956055,  0.25976562,  0.15332031,  0.15136719,  0.08300781,
       -0.15527344,  0.04931641,  0.07519531, -0.05078125, -0.1328125 ,
       -0.13574219,  0.04199219, -0.14257812,  0.02099609,  0.07861328,
        0.01611328,  0.01623535, -0.21582031,  0.01599121, -0.04882812,
       -0.02404785,  0.13476562,  0.08496094, -0.01196289,  0.10009766,
       -0.13867188,  0.08056641, -0.22070312, -0.12011719,  0.18945312,
        0.05444336, -0.05053711,  0.00147247,  0.14160156, -0.06494141,
       -0.05566406, -0.09033203, -0.0267334 , -0.10498047,  0.02416992,
        0.01422119,  0.1875    , -0.16503906,  0.01538086, -0.04174805,
        0.05444336, -0.01184082, -0.15625   ,  0.00193024, -0.06982422],
      dtype=float32)

In [4]:
wv["good"].shape

(300,)

In [5]:
import pandas as pd

In [6]:
df=pd.read_csv("Fake_Real_Data.csv")
df.head()

                                                Text label
0   Top Trump Surrogate BRUTALLY Stabs Him In The...  Fake
1  U.S. conservative leader optimistic of common ...  Real
2  Trump proposes U.S. tax overhaul, stirs concer...  Real
3   Court Forces Ohio To Allow Millions Of Illega...  Fake
4  Democrats say Trump agrees to work on immigrat...  Real

In [7]:
df.label.value_counts()
# to check any class imbalance

label
Fake    5000
Real    4900
Name: count, dtype: int64

In [8]:
df['label_num']=df['label'].map({"Fake":0,"Real":1})
df.head()

                                                Text label  label_num
0   Top Trump Surrogate BRUTALLY Stabs Him In The...  Fake          0
1  U.S. conservative leader optimistic of common ...  Real          1
2  Trump proposes U.S. tax overhaul, stirs concer...  Real          1
3   Court Forces Ohio To Allow Millions Of Illega...  Fake          0
4  Democrats say Trump agrees to work on immigrat...  Real          1

In [9]:
import spacy
nlp=spacy.load("en_core_web_lg")


def preprocess_and_vectorize(text):
    doc=nlp(text)
    
    filtered_tokens=[]
    for token in doc:
        if token.is_stop or token.is_punct:
            continue
        filtered_tokens.append(token.lemma_)
    return wv.get_mean_vector(filtered_tokens)

In [10]:
preprocess_and_vectorize("ok, don't worry,come and meet me tomorrow").shape

(300,)

In [12]:
df["vector"]=df['Text'].apply(lambda text:preprocess_and_vectorize(text))
df.head()
# it takes atleast 15 minutes to run

,Text,label,vector
0,Top Trump Surrogate BRUTALLY Stabs Him In The...,Fake,"[0.008657642, 0.019024342, -0.011917442, 0.032..."
1,U.S. conservative leader optimistic of common ...,Real,"[0.010864096, 0.007960429, 0.0011915653, 0.014..."
2,"Trump proposes U.S. tax overhaul, stirs concer...",Real,"[0.018134918, 0.0062743523, -0.005872244, 0.03..."
3,Court Forces Ohio To Allow Millions Of Illega...,Fake,"[0.01255197, 0.012613623, 5.9780963e-05, 0.021..."
4,Democrats say Trump agrees to work on immigrat...,Real,"[-0.0019059887, 0.011889367, 0.0035395357, 0.0..."

In [16]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df.vector.values,df.label_num,test_size=0.2,random_state=1,stratify=df.label_num)

In [17]:
import numpy as np

In [19]:
x_train.shape

(7920,)

In [20]:
x_test.shape

(1980,)

In [21]:
# converting x_train,x_test as 2d array using numpy stack function
x_train=np.stack(x_train)
x_test=np.stack(x_test)

In [22]:
x_train.shape

(7920, 300)

In [23]:
x_test.shape

(1980, 300)

In [25]:
from sklearn.ensemble import GradientBoostingClassifier

model=GradientBoostingClassifier()
model.fit(x_train,y_train)

GradientBoostingClassifier()

In [29]:
y_test[:5]

1883    0
7747    1
5898    0
3335    1
8173    1
Name: label_num, dtype: int64

In [30]:
y_pred=model.predict(x_test)
y_pred[:5]

array([0, 1, 0, 1, 1], dtype=int64)

In [28]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      0.98      0.98      1000
           1       0.98      0.99      0.98       980

    accuracy                           0.98      1980
   macro avg       0.98      0.98      0.98      1980
weighted avg       0.98      0.98      0.98      1980